### PR TITLE
New zocalo.util.rabbitmq.RabbitMQAPI

### PR DESCRIPTION
**Pull request by rjgildea**
Provide a (not fully comprehensive) Python wrapper around the [RabbitMQ HTTP API](https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.9.7/deps/rabbitmq_management/priv/www/api/index.html). Can be used to read various metrics useful for monitoring/health checks, and configuring exchanges, policies, queues, etc.

Adds explicit dependencies on [pydantic](https://pydantic-docs.helpmanual.io/) and [requests](https://docs.python-requests.org/) modules and a test dependency on [requests-mock](https://requests-mock.readthedocs.io/en/latest/).

Alternative to #136

### CODE REVIEW

**Comment by d-j-hatton** [comment]
I used a `singledispatchmethod` in the configuration script that this has inherited because we didn't need to worry about python versions there (`singledispatchmethod` was new in 3.8). Does this need a slight rewrite to fix the test failures related to this, or do we want to drop the `singledispatch` in favour of a more `{exchange, queue}_{declare, delete}` design?

**Comment by rjgildea** [comment]
> I used a `singledispatchmethod` in the configuration script that this has inherited because we didn't need to worry about python versions there (`singledispatchmethod` was new in 3.8). Does this need a slight rewrite to fix the test failures related to this, or do we want to drop the `singledispatch` in favour of a more `{exchange, queue}_{declare, delete}` design?

Since the `singledispatch` mode was added _after_ the explicit `{exchange, queue}_{declare, delete}` versions, it should only need a relatively straightforward revert of a [single commit](https://github.com/DiamondLightSource/python-zocalo/pull/140/commits/3f123dee9a63c8d5204f7fa45233ef6fadd5f054). The updated version of the server configuration script that uses the API would need a bit of re-working to use the explicit methods, but obviously not insurmountable.

**Comment by d-j-hatton** [comment]
> > I used a `singledispatchmethod` in the configuration script that this has inherited because we didn't need to worry about python versions there (`singledispatchmethod` was new in 3.8). Does this need a slight rewrite to fix the test failures related to this, or do we want to drop the `singledispatch` in favour of a more `{exchange, queue}_{declare, delete}` design?
> 
> Since the `singledispatch` mode was added _after_ the explicit `{exchange, queue}_{declare, delete}` versions, it should only need a relatively straightforward revert of a [single commit](https://github.com/DiamondLightSource/python-zocalo/pull/140/commits/3f123dee9a63c8d5204f7fa45233ef6fadd5f054). The updated version of the server configuration script that uses the API would need a bit of re-working to use the explicit methods, but obviously not insurmountable.

I think either way is fairly simple. The single dispatch method could just be changed to call a single dispatch that doesn't live inside the class. I don't mind either direction. Any preferences?

**Comment by rjgildea** [comment]
> > > I used a `singledispatchmethod` in the configuration script that this has inherited because we didn't need to worry about python versions there (`singledispatchmethod` was new in 3.8). Does this need a slight rewrite to fix the test failures related to this, or do we want to drop the `singledispatch` in favour of a more `{exchange, queue}_{declare, delete}` design?
> > 
> > 
> > Since the `singledispatch` mode was added _after_ the explicit `{exchange, queue}_{declare, delete}` versions, it should only need a relatively straightforward revert of a [single commit](https://github.com/DiamondLightSource/python-zocalo/pull/140/commits/3f123dee9a63c8d5204f7fa45233ef6fadd5f054). The updated version of the server configuration script that uses the API would need a bit of re-working to use the explicit methods, but obviously not insurmountable.
> 
> I think either way is fairly simple. The single dispatch method could just be changed to call a single dispatch that doesn't live inside the class. I don't mind either direction. Any preferences?

I've removed the `functools.singledispatchmethod` use here, and then in our configuration script we can just [extend the API to add the `{create,delete}_component` methods](https://gitlab.diamond.ac.uk/scisoft/zocalo/-/commit/8b3e0652eb7f6d94932caddc6b546b1559f33c54) where we don't have the limitation of supporting Python prior to 3.8.

**Review by d-j-hatton — APPROVED** [review]

**Pull request merged**
