### PR TITLE
site configuration for zocalo

### PR DESCRIPTION
**Pull request by Anthchirp**
Allow site-specific configuration by pointing to a modular configuration file, which can be used to set up logging, messaging, etc.

This PR is partially extracted from #52.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Soo... I think this is at a stage now where people can take a look at it.

It implements most of the suggested configuration features. Configuration files are validated using marshmallow and against the general file schema and any known plugin schemas. Plugins are registered using entry points. I decided to disallow setting random strings in the configuration (because then the overall schema allows kind of everything), and instead implemented a storage plugin that can store any arbitrary key-value stuff.

A bunch of tests are included.

Things to be done:
* the recursive configuration bits are still missing, so including other files doesn't work yet
* documentations needs to be beefed up, including a description of the plugin API
* the JMX plugin could be replaced by the storage plugin - but then it wouldn't have parameter validation. Keeping it is fine, but I haven't yet implemented the `activate` function.
* just before merging the stomp plugin should be removed here and go into the workflows package instead.

**Comment by stufisher** [comment]
Looks good to me.

I think theres a couple of bits of config left to apply:
* zocalo.go (https://github.com/DiamondLightSource/python-zocalo/pull/52/files#diff-cd8aefc90e3825d23665a02a0fe60ddaeea5587a0a37e2b07554fb19abd353e7, you may not want to remove -f at the same time)
* zocalo.wrap (https://github.com/DiamondLightSource/python-zocalo/pull/52/files#diff-e8aa120e21137d9d11e53a19f863071d2224d06f81e6c405ff834383863b7c0b)

**Comment by Anthchirp** [comment]
Made the changes to `zocalo.go` and `zocalo.wrap`. And with workflows 2.7 for the stomp plugin it works \o/

**Comment by stufisher** [comment]
Prolly want to apply the storage plugin to this hardcoded path too:
https://github.com/DiamondLightSource/python-zocalo/blob/5c26dfe57f1b5ca2bbfd6b253ecfbff9831a3fbc/src/zocalo/cli/go.py#L142

**Comment by Anthchirp** [comment]
I'd be happy to merge this now, turn it into a release and pick up the remaining bits in separate issues

**Pull request merged**
