### PR TITLE
try to make env activation consistent and reusable

### PR DESCRIPTION
**Pull request by stufisher**
~~The default default is "live", which i think is sensible based on cli tools. Services default to test~~
Makes environment activation blocks consistent between go, wrap, and service instantiation. Default envs for cli tools and services can now be defined in the config under the `defaults` property.

### CODE REVIEW

**Comment by stufisher** [comment]
I could improve this a little more, we could add something like:
```
default:
    service: test
    cli: live
```
to the config, then `live` and `test` no longer have any meaning, then tell Configuration what its caller is, by replacing default_env with caller or something.

**Comment by stufisher** [comment]
Now possible to define defaults in the config

**Review by Anthchirp — COMMENTED** [review]
I'm thinking having two default environments is not very accessible.
Having a `service` and a `cli` default doesn't really help, as I wouldn't be able to explain why there are these two, and what exactly each group includes. And why the services command is not included in cli (even though it is run on the command line), and why the shutdown command is (even though it operates on service instances).

I'm thinking maybe we should only have one `default` environment and use that as the default.
To avoid having less useful environment names we could add aliasing support like so:

```yaml
environments:
  live:
    - this
    - that
    - other

  test:
    - this
    - that
    - third thing

  default: live
```

That would also keep the statement at https://zocalo.readthedocs.io/en/latest/siteconfig.html#configuration-file-format, that there are only three different types of things on the top level configuration file, true.

What do you think?

**Comment by stufisher** [comment]
I can refactor it to do that if you like. I was just trying to mimic the existing behaviour, its clear i think that cli tools need to start in the live env, people dont want to `zocalo.go --live` all the time, so its up to you if you are ok with developers starting test services accidentally in the live env (im the only dev working on this at esrf right now, so not a problem here)

**Comment by Anthchirp** [comment]
Okay, let's do that then

**Comment by stufisher** [comment]
Done

**Review by Anthchirp — APPROVED** [review]
Does this work for you?

**Pull request merged**
